---

- name: Show all Access-lists
  hosts: Cisco_Devices
  gather_facts: false
  vars:
    - number: "125" ##update number
  tasks:
    - name: Show Access-list
      ios_command:
        commands:
          - sh access-list
      register:  config

    - name: Print results
      debug:
        var: config.stdout_lines

    - name: create access-list to allow access to Support1
      ios_command:
        commands:
          - config t
          - ip access-list extended 101
          - no {{ 125 }}
          - do sh access-lists

      register:  config2

    - name: Print results
      debug:
        var: config2.stdout_lines

